services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: modu-bot-qdrant
    restart: always
    ports:
      - "8001:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
